#!/bin/sh

#   toaac 1.3
#
#   Convierte todos los archivos MP3 en el directorio actual a formato
#   AAC 64 Kbps mono, manteniendo las tags.
#   Al finalizar queda en el directorio actual una carpeta de igual nombre
#   con los archivos .m4a y la imagen Cover.jpg (o Front.jpg) en tamaño
#   500x500.
#
#   Requiere:
#   - avconv
#
#
#   Creado por Juan Bertinetti (juanbertinetti@gmail.com)
#
#   Cambios:
#   -1.3 (2 de diciembre de 2013):
#       Cambiado faac por avconv ...


#   -1.2 (30 de abril de 2012):
#       Cambiada la extensión de salida de los archivos de .aac a .m4a (de
#       esta forma los archivos son reconocidos de forma correcta en todos
#       los reproductores).
#   -1.1:
#       También se fija en el nombre de imagen Front.jpg aparte de Cover.jpg.
#   -1.0 (26 de octubre de 2011):
#       Versión inicial.
#
#   Este programa es Software Libre.
#

#while getopts "m" optname
#do
    #case "$optname" in
        #"m")
            #MONO=True
            #DB_PORT="$OPTARG";
        #"?")
            #echo "Unknown option $OPTARG";
            #;;
        #":")
            #echo "No argument value for option $OPTARG";
            #;;
        #*)
            #echo "Unknown error while processing options";
            #;;
    #esac
#done

mkdir aac
for i in *.ogg; do
    #avconv -i "${i}" -b 64k -ac 1 -map_metadata 0:g "aac/${i}.m4a"
    avconv -i "${i}" -b 64k "aac/${i}.m4a"
done
if (test -f Cover.jpg) then
    convert Cover.jpg -resize 500x500 aac/Cover.jpg;
elif (test -f Front.jpg) then
    convert Front.jpg -resize 500x500 aac/Cover.jpg;
fi
#rm mediainfo.txt
cd aac
rename 's/.ogg//' *.m4a
cd ..
mv aac "${PWD##*/}"
